[package]
title = "OmniGibson Remote Viewer Session API"
version = "0.1.0"
description = "Adds a lightweight session metadata endpoint for the OmniGibson remote viewer."
authors = ["OmniGibson"]

[dependencies]
"omni.services.core" = {}
"omni.services.transport.server.http" = {}

[[python.module]]
name = "omnigibson.remote_viewer.session"


